name: .NET CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore NuGet packages
      run: nuget restore Ahorcado.sln
    
    # Deploy to Prod and run Acceptance Tests
    - name: Build with dotnet
      run: dotnet build --configuration Release .\ahorcado

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o ahorcado .\ahorcado

    - name: Deploy to Production
      run: |
        iisreset /stop
        Copy-Item C:/Users/paola.giorsetti/Desktop/Ahorcado/Ahorcado.MVC/* C:/inetpub/wwwroot/ahorcadoweb -Recurse -Force
        iisreset /start
    
    - name: Curl the website as a smoke test
      run: curl http://localhost

    - name: Run Acceptance Tests
      run: |
        dotnet build --configuration Release .\Ahorcado.UIAutomation
        cd .\Ahorcado.UIAutomation
        dotnet test