name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore NuGet packages
      run: nuget restore Ahorcado.sln
    - name: Build Net Framework
      run: msbuild Ahorcado.sln 
    - name: Build Net Core
      run: dotnet build --no-restore
    - name: Test and Code Coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
